name: Deploy and Build on Server

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH and Run Build
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            # Exportar el PATH para asegurar que detecte pnpm y node
            export PATH=$PATH:/usr/local/bin:~/.nvm/versions/node/$(ls ~/.nvm/versions/node 2>/dev/null | tail -n 1)/bin:~/.local/share/pnpm

            # Navegar al proyecto y actualizar código
            cd /root/scoundrels-quest
            git pull

            # Frontend: instalar y compilar
            cd ./front
            pnpm install
            pnpm run build

            # Backend: reiniciar contenedor
            cd ../back
            docker compose down
            docker compose up -d --build